
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'statementsASSIGN DIVIDE ID LET LPAREN MINUS MUT NUMBER PLUS RPAREN SEMICOLON TIMESstatements : statements statementstatements : statementstatement : LET ID ASSIGN expression SEMICOLONstatement : LET MUT ID ASSIGN expression SEMICOLONstatement : ID ASSIGN expression SEMICOLON\nexpression : expression PLUS term\n           | expression MINUS term\nexpression : term\nterm : term TIMES factor\n     | term DIVIDE factor\nterm : factorfactor : NUMBERfactor : IDfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'LET':([0,1,2,5,19,25,32,],[3,3,-2,-1,-5,-3,-4,]),'ID':([0,1,2,3,5,7,8,9,16,18,19,20,21,22,23,25,32,],[4,4,-2,6,-1,10,11,11,11,11,-5,11,11,11,11,-3,-4,]),'$end':([1,2,5,19,25,32,],[0,-2,-1,-5,-3,-4,]),'MUT':([3,],[7,]),'ASSIGN':([4,6,10,],[8,9,18,]),'NUMBER':([8,9,16,18,20,21,22,23,],[15,15,15,15,15,15,15,15,]),'LPAREN':([8,9,16,18,20,21,22,23,],[16,16,16,16,16,16,16,16,]),'TIMES':([11,13,14,15,27,28,29,30,31,],[-13,22,-11,-12,22,22,-9,-10,-14,]),'DIVIDE':([11,13,14,15,27,28,29,30,31,],[-13,23,-11,-12,23,23,-9,-10,-14,]),'SEMICOLON':([11,12,13,14,15,17,26,27,28,29,30,31,],[-13,19,-8,-11,-12,25,32,-6,-7,-9,-10,-14,]),'PLUS':([11,12,13,14,15,17,24,26,27,28,29,30,31,],[-13,20,-8,-11,-12,20,20,20,-6,-7,-9,-10,-14,]),'MINUS':([11,12,13,14,15,17,24,26,27,28,29,30,31,],[-13,21,-8,-11,-12,21,21,21,-6,-7,-9,-10,-14,]),'RPAREN':([11,13,14,15,24,27,28,29,30,31,],[-13,-8,-11,-12,31,-6,-7,-9,-10,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,5,]),'expression':([8,9,16,18,],[12,17,24,26,]),'term':([8,9,16,18,20,21,],[13,13,13,13,27,28,]),'factor':([8,9,16,18,20,21,22,23,],[14,14,14,14,14,14,29,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',11),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',15),
  ('statement -> LET ID ASSIGN expression SEMICOLON','statement',5,'p_statement_let','parser.py',23),
  ('statement -> LET MUT ID ASSIGN expression SEMICOLON','statement',6,'p_statement_let_mut','parser.py',35),
  ('statement -> ID ASSIGN expression SEMICOLON','statement',4,'p_statement_assign','parser.py',47),
  ('expression -> expression PLUS term','expression',3,'p_expression_binop','parser.py',66),
  ('expression -> expression MINUS term','expression',3,'p_expression_binop','parser.py',67),
  ('expression -> term','expression',1,'p_expression_term','parser.py',76),
  ('term -> term TIMES factor','term',3,'p_term_binop','parser.py',85),
  ('term -> term DIVIDE factor','term',3,'p_term_binop','parser.py',86),
  ('term -> factor','term',1,'p_term_factor','parser.py',100),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',108),
  ('factor -> ID','factor',1,'p_factor_id','parser.py',113),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',122),
]
