
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'statementsASSIGN ID LET MUT NUMBER SEMICOLONstatements : statements statementstatements : statementstatement : LET ID ASSIGN NUMBER SEMICOLONstatement : LET MUT ID ASSIGN NUMBER SEMICOLONstatement : ID ASSIGN NUMBER SEMICOLON'
    
_lr_action_items = {'LET':([0,1,2,5,14,15,17,],[3,3,-2,-1,-5,-3,-4,]),'ID':([0,1,2,3,5,7,14,15,17,],[4,4,-2,6,-1,10,-5,-3,-4,]),'$end':([1,2,5,14,15,17,],[0,-2,-1,-5,-3,-4,]),'MUT':([3,],[7,]),'ASSIGN':([4,6,10,],[8,9,13,]),'NUMBER':([8,9,13,],[11,12,16,]),'SEMICOLON':([11,12,16,],[14,15,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',8),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',12),
  ('statement -> LET ID ASSIGN NUMBER SEMICOLON','statement',5,'p_statement_let','parser.py',16),
  ('statement -> LET MUT ID ASSIGN NUMBER SEMICOLON','statement',6,'p_statement_let_mut','parser.py',21),
  ('statement -> ID ASSIGN NUMBER SEMICOLON','statement',4,'p_statement_assign','parser.py',26),
]
